/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * openobd
 * Copyright (C) Simon Booth 2010 <simesb@users.sourceforge.net>
 *
 * openobd is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * openobd is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __dlgOptions__
#define __dlgOptions__

/**
@file
Subclass of dlgBaseOptions, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "obdbase.h"

struct obdOptions {
	bool imperial;
	wxString port;
};

/** Implementing dlgBaseOptions */
class dlgOptions : public dlgBaseOptions
{
public:
	/** Constructor */
	dlgOptions( wxWindow* parent, obdbase* device, struct obdOptions* opts );

	void onOK( wxCommandEvent& event );

protected:
	obdbase* obd;
	struct obdOptions* options;
};

#endif // __dlgOptions__
