/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * openobd
 * Copyright (C) Simon Booth 2010 <simesb@users.sourceforge.net>
 *
 * openobd is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * openobd is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __pidPanel__
#define __pidPanel__

/**
@file
Subclass of pidBasePanel, which is generated by wxFormBuilder.
*/

#include <sqlite3.h>
#include "gui.h"
#include "obdbase.h"

/** Implementing pidBasePanel */
class pidPanel : public pidBasePanel
{
protected:
	// Handlers for pidBasePanel events.
	void onRefreshClick( wxCommandEvent& event );

public:
	/** Constructor */
	pidPanel( wxWindow* parent, obdbase* device, sqlite3* sql  );
	void updateDevice(obdbase* device);

private:
    obdbase* obd;
    sqlite3* db;
};

#endif // __pidPanel__
